# Dockerfile for Sozialkompass-Frontend using node and nginx
# Current platform is amd64
FROM --platform=amd64 node:19.2.0-alpine as build-step
WORKDIR /app
COPY ./frontend/package.json ./
COPY ./frontend/src ./src
COPY ./frontend/public ./public
RUN yarn install --network-timeout 300000
RUN yarn build

# creates nginx server
FROM --platform=amd64 nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf