# Docker-Compose file for perfect setup
# Builds frontend(client) and backend(api) and pulls Mongo 4.4.6
# Also it exposes Port 80 for frontend
services:
  api:
    container_name: sozialkompass-api
    build:
      context: .
      dockerfile: Dockerfile.api
    image: react-flask-app-api
    ports:
      - "5000:5000"
  client:
    container_name: sozialkompass-client
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    ports:
      - "80:80"
  database:
    image: mongo:4.4.6
    container_name: mongodb
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=goodPW
    ports:
      - "27017:27017"
    volumes:
      - mongoData:/mongoData/db
volumes:
  mongoData:
